## NumPy : Practice Problems 1
Easy Questions : 7
Moderate Questions : 7
Hard Questions : 3
<hr>


### 1. Write a NumPy program to get the numpy version and show numpy build configuration.

Level: Easy

In [1]:
import numpy as np

print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\Users\\anjel\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


### 2. Create a null vector of size 10 but the fifth value which is 1.

Level: Easy

In [2]:
ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###  Create a vector with values ranging from 10 to 49.

Level: Easy

In [4]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. create two arrays and stack them vertically

Level: Easy

In [22]:
a = np.arange(5,20)
b = np.arange(10,25)
print(np.vstack((a,b)))

[[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]


### 4. Reverse a vector (first element becomes last).

Level: Easy

In [8]:
arr=np.array([1,2,3,4,5,6])
rev=arr[::-1]
print(rev)

[6 5 4 3 2 1]


### 5. Create a 3x3 matrix with values ranging from 0 to 8 

Level: Easy

In [15]:
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6. Find indices of non-zero elements from [1,2,0,0,4,0]

Level: Easy

In [24]:
x=np.array([1,2,0,0,4,0])
print(np.nonzero(x))
print(x[np.nonzero(x)])





(array([0, 1, 4], dtype=int64),)
[1 2 4]


### 7. Create a 10x10 array with random values and find the minimum and maximum values.

Level: Easy

In [55]:
arr=np.random.randint(0,101,(10,10))
print(arr)

print('max of array is :%s\n  '%np.max(arr))
print('min value:%s\n '%np.min(arr))


[[ 27  80  95  27  87  51  79  27  69 100]
 [ 81  14  91  29  27  37  68  13  85  11]
 [ 95  61  86  22  79  45   0  91  75  11]
 [ 23  76  53  59  44  29   8   9  13  82]
 [ 50  93  12  62  15  97   6   1  34   6]
 [ 50  12  18  24  39  44  75  83  39  16]
 [ 83  36  55  62  82  84  83  17  35  73]
 [  7  95  83  38  58  86  61  23  22  40]
 [ 94  92   3  93  89  30  93  89  63  41]
 [ 56  83  65  15  11  87   4  25  44  58]]
max of array is :100
  
min value:0
 


### 8. Create a random vector of size 30 and find the mean value.

Level: Medium

In [63]:
ran_vec = np.random.random(30)
print(ran_vec)
np.mean(ran_vec)

[0.71424105 0.17356926 0.59921544 0.17496361 0.18616329 0.62601222
 0.11948365 0.64667303 0.26797242 0.16942792 0.60160212 0.91672373
 0.53287259 0.10255991 0.19512303 0.72108287 0.47924048 0.62672642
 0.93783317 0.5910286  0.13846076 0.22987031 0.81863482 0.5209301
 0.64812574 0.50095669 0.67234905 0.74348406 0.26534867 0.69066991]


0.4870448315350679

### 9. Create a 2d array with 1 on the border and 0 inside
Level: Medium

In [85]:
oneborder = np.ones((10,10))
oneborder[1:-1]
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 10. How to add a border (filled with 0's) around an existing array

Level: Medium

In [86]:
x = np.pad(oneborder, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Sample Output:
    
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]
 
 Level: Medium

In [128]:
mat=np.zeros((5,5))
mat.diagonal(offset=1)
mat[1,0]=1
mat[2,1]=2
mat[3,2]=3
mat[4,3]=4
mat

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

### 12. Create a 5*5 matrix with random values and normalize it.
Level: Medium

In [120]:
np.random.seed(8)
ran_value=np.random.randint(1,11,(5,5))
sum_of_rows = ran_value.sum(axis=1)
norm_arr = ran_value/sum_of_rows
print('original:%s'%ran_value)
print("after Normalization :%s" %norm_arr)

original:[[ 4  5  2 10  6]
 [ 9  4  9  1  6]
 [ 2  4 10  3  3]
 [ 7  9 10  4  5]
 [ 6  6  8 10  3]]
after Normalization :[[0.14814815 0.17241379 0.09090909 0.28571429 0.18181818]
 [0.33333333 0.13793103 0.40909091 0.02857143 0.18181818]
 [0.07407407 0.13793103 0.45454545 0.08571429 0.09090909]
 [0.25925926 0.31034483 0.45454545 0.11428571 0.15151515]
 [0.22222222 0.20689655 0.36363636 0.28571429 0.09090909]]


### 13. How to find common values between two arrays
Level: Medium

In [125]:
a= np.array([1,2,3,7,5])
b=np.array([0,2,5,1])
print(np.intersect1d(a,b))



[1 2 5]


### 14. Consider a generator function that generates 10 integers and use it to build an array
Level: Medium

### 15. Subtract the mean of each row of a matrix
Level: Hard

In [135]:

arr = np.random.rand(2,3)
res = arr - arr.mean(axis = 1,keepdims=True)
print(arr)
res

[[0.27057352 0.47622391 0.60961621]
 [0.18725043 0.02799537 0.20399355]]


array([[-0.18156436,  0.02408603,  0.15747833],
       [ 0.04750398, -0.11175108,  0.0642471 ]])

### 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
Level: Hard

### 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Level: Hard

In [137]:
arr = np.arange(5, 50, 10)
arr

array([ 5, 15, 25, 35, 45])